/**
 * Per-state HS NIL rules — the rich dataset that backs the public
 * /state-rules page and the athlete dashboard "Your state's rules" card.
 *
 * Distinct from `nilStatus.ts`, which holds the simpler on/partial/off flag
 * that gates signup and drives map color. This file holds the full per-state
 * rule readout for users to consult.
 *
 * IMPORTANT — DATA STATUS: Only the five states marked `documented: true`
 * (CA, TX, FL, NY, GA) have been seeded with researched values. Every other
 * state defaults to `documented: false` with neutral placeholders, surfaced
 * to users as "Documentation in progress." All seeded data is sourced from
 * each state association's published HS NIL policy circa 2024-2025 and MUST
 * be verified by a sports/entertainment attorney before public launch — see
 * `project_pre_launch_tasks.md`.
 */

import { HS_NIL_STATUS, type HsNilStatus } from "./nilStatus";

export type NotarizationRule = "none" | "minor-only" | "required";

export type StateRules = {
  code: string;
  name: string;
  hsNilAllowed: HsNilStatus;
  parentalConsentRequired: boolean;
  parentalCosignOnDeals: boolean;
  notarization: NotarizationRule;
  schoolApprovalRequired: boolean;
  schoolDisclosureRequired: boolean;
  bannedCategories: string[];
  notes: string;
  sourceLabel?: string;
  sourceUrl?: string;
  lastUpdated: string;
  documented: boolean;
};

const STANDARD_BANNED = [
  "alcohol",
  "tobacco",
  "cannabis",
  "gambling",
  "firearms",
  "adult content",
  "performance-enhancing supplements",
];

const SEEDED: Record<string, StateRules> = {
  AK: {
    code: "AK",
    name: "Alaska",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Alaska permits HS NIL as long as the deal has no school, team, ASAA region, or ASAA affiliation. Athletes (e.g. Olympic swimmer Lydia Jacoby) have signed major commercial endorsements while in HS. Don't use school marks, uniforms, or facilities; standard prohibited-category list applies as a default contract guardrail because ASAA's published policy does not enumerate one.",
    sourceLabel: "ASAA Handbook, Article 8 Section 1 & 2 (Amateurism / NIL)",
    sourceUrl: "https://asaa.org/resources/handbook/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  AL: {
    code: "AL",
    name: "Alabama",
    hsNilAllowed: "off",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Alabama HS NIL is NOT permitted. Under AHSAA's Amateur Rule (Section 8), any compensation tied to athletic identity results in immediate ineligibility. Legislative efforts (HB 489, 2025) have not yet changed this. Do not sign any NIL deal while you are an AHSAA-eligible high school athlete.",
    sourceLabel: "AHSAA Handbook 2025-2026, Amateur Rule (Section 8)",
    sourceUrl: "https://new.ahsaa.com/Portals/0/Publications/2025-2026/Handbook%202025-2026.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  AR: {
    code: "AR",
    name: "Arkansas",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Arkansas HS NIL is restricted: under Act 589 (2023) and HB 1649, HS athletes can only sign NIL deals after they have been admitted to, signed a National Letter of Intent with, or otherwise enrolled at an Arkansas college. Pre-commitment HS athletes still fall under the AAA's amateur rule, which prohibits compensation for use of their name or image. Additional 2025 update: NIL income is exempt from Arkansas state income tax.",
    sourceLabel: "Arkansas Act 589 (2023) / AAA Amateur Rule (Rule 10)",
    sourceUrl: "https://ahsaa.org/handbook",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  AZ: {
    code: "AZ",
    name: "Arizona",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "controlled substances", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Arizona permits HS NIL but with disclosure: within 5 school days of entering an NIL agreement, the student or parent/guardian must notify the school's Athletic Director. Deals cannot use school marks, uniforms, mascots, AIA logos, or school facilities, and cannot be funded by schools, boosters, collectives, or coaches. Endorsements that conflict with the school district's policy (tobacco, alcohol, controlled substances) are prohibited.",
    sourceLabel: "AIA Bylaws Article 15, Section 15.11 (Student Eligibility / NIL)",
    sourceUrl: "https://aiaonline.org/files/65/article-15-student-eligibility-rules.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  CA: {
    code: "CA",
    name: "California",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "California permits HS NIL under CIF Bylaws 212 (Amateur Status) and 510 (Undue Influence). Athletes cannot use school or team affiliations, uniforms, logos, or any school identifiers; deals must be reported to the school/athletic program. Some schools may also require pre-approval or contract submission, and individual schools may restrict additional categories (e.g. cannabis, gambling, adult content) beyond the CIF baseline. NIL income is not capped.",
    sourceLabel: "CIF Bylaw 212 (Amateur Status) and Bylaw 510 (Undue Influence)",
    sourceUrl: "https://www.cifstate.org/governance/constitution/index",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  CO: {
    code: "CO",
    name: "Colorado",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Colorado permits HS NIL under CHSAA Article 20 (Bylaws 2000.1-2000.8). The deal must have NO connection to your CHSAA school, team, or activity program: no jerseys, no school grounds, no mascots, no team-name references. CHSAA tightened the bylaw language for the 2025-26 season for clarity but did not change what is allowed.",
    sourceLabel: "CHSAA Bylaws Article 20, Sections 2000.1-2000.8 (Amateur Status / NIL)",
    sourceUrl: "https://chsaanow.com/news/2025/7/8/chsaa-bylaw-changes-for-2025-26-have-gone-into-effect.aspx",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  CT: {
    code: "CT",
    name: "Connecticut",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "controlled substances", "gambling", "firearms", "adult content"],
    notes: "Connecticut permits HS NIL under CIAC Article 12, Rule 4.5.A (amended June 2022). Athletes must disclose agreements to the school and cannot use school marks. CIAC explicitly prohibits endorsements of adult entertainment, tobacco, cannabis, controlled substances, weapons, and gambling. Athletes may engage attorneys or agents.",
    sourceLabel: "CIAC Handbook Article 12, Rule 4.5.A (Amateur Athletic Guidelines / NIL)",
    sourceUrl: "https://www.casciac.org/pdfs/eligibility_brochure.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  DC: {
    code: "DC",
    name: "District of Columbia",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "DC permits HS NIL under the DCSAA NIL Policy (2022-23 handbook update). Deals must not include any school team, school, or DCSAA affiliation, name, or logo. The DCSAA requires written notification of all commercial or marketing endorsements (no fixed reporting deadline). DC was the 17th jurisdiction to adopt HS NIL.",
    sourceLabel: "DCSAA NIL Policy Guide (Handbook 2022-23)",
    sourceUrl: "https://www.dcsaasports.com/nil/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  DE: {
    code: "DE",
    name: "Delaware",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "gambling", "cannabis", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Delaware permits HS NIL under DIAA Regulation 1030 (effective 2024-25 school year). Athletes must inform their athletic director within 72 hours of signing an NIL contract, or before the next scheduled athletic event, whichever comes first. Compensation cannot be contingent on athletic performance, cannot be an enrollment incentive, and cannot come from the school. Endorsements of tobacco, alcohol, and gambling are explicitly prohibited; deals cannot use school marks, apparel, or facilities.",
    sourceLabel: "DIAA Regulation 1030 (Student Athlete Eligibility - Amateur Status / NIL)",
    sourceUrl: "https://education.delaware.gov/diaa/diaa_for/parents/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  FL: {
    code: "FL",
    name: "Florida",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances", "performance-enhancing supplements"],
    notes: "Florida permits HS NIL under FHSAA Bylaw 9.9 (Amateurism), approved June 5, 2024 and ratified by the State Board of Education July 24, 2024. Because most HS athletes are minors, a parent or guardian must co-sign any NIL contract. NIL agreements expire at HS graduation. Prohibited: NIL collectives, gambling, adult entertainment, alcohol, tobacco/vaping/nicotine, cannabis, controlled substances, weapons/firearms/ammunition. Deals cannot use school uniforms, equipment, logos, or branding. NIL cannot be used as a recruiting inducement.",
    sourceLabel: "FHSAA Bylaw 9.9 (Amateurism / NIL)",
    sourceUrl: "https://fhsaa.com/sports/2024/8/12/ABOUT_NILResources.aspx",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  GA: {
    code: "GA",
    name: "Georgia",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "controlled substances", "gambling", "adult content"],
    notes: "Georgia (GHSA) allows NIL but bans use of school marks/uniforms/facilities and bans participation in collectives or NIL clubs. Athlete or parent must notify the principal or athletic director within 7 calendar days of signing any NIL contract; compensation cannot be tied to athletic performance or used as an enrollment inducement.",
    sourceLabel: "GHSA Constitution Appendix N (Guidelines Regarding Name, Image and Likeness)",
    sourceUrl: "https://www.ghsa.net/constitution-section-2025-2026-appendix-n-guidelines-regarding-name-image-and-likeness",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  HI: {
    code: "HI",
    name: "Hawaii",
    hsNilAllowed: "off",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "Hawaii (HHSAA) does not permit NIL for high school athletes. HHSAA amateurism rules treat athletic-related compensation as forfeiture of amateur status, and the association has not adopted a high school NIL policy. Engaging in NIL deals can render an athlete ineligible.",
    sourceLabel: "HHSAA Administrative Regulations (Amateur Status)",
    sourceUrl: "https://hhsaa.org/assets/content/resources/governing_documents/Administrative-Regulations.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  IA: {
    code: "IA",
    name: "Iowa",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances", "weapons"],
    notes: "Iowa (IHSAA / IGHSAU) allows NIL provided compensation is not contingent on athletic performance and is not used as a school recruiting inducement. Athletes may not use the IHSAA/IGHSAU or member-school names, mascots, logos, or facilities, and schools and booster clubs may not pay athletes. Prohibited categories include gaming/gambling, alcohol, tobacco, cannabis, illegal/banned substances, adult entertainment, and weapons.",
    sourceLabel: "IHSAA Name, Image, Likeness (NIL) Guidance",
    sourceUrl: "https://www.iahsaa.org/handbook/name-image-likeness-guidance/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  ID: {
    code: "ID",
    name: "Idaho",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances", "weapons"],
    notes: "Idaho (IHSAA) allows NIL under Rule 8-4-1 (Amateur Status) provided there is no school, league, district or IHSAA affiliation, no use of school marks/facilities, and compensation is not contingent on athletic performance. Families are advised to consult the school for guidance.",
    sourceLabel: "Idaho IHSAA Rule 8 - Individual Eligibility (NIL)",
    sourceUrl: "https://idhsaa.org/asset/Rules%20&%20Regs/RULE%208%2025-26.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  IL: {
    code: "IL",
    name: "Illinois",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances", "weapons"],
    notes: "Illinois (IHSA) permits NIL under By-law 3.084. Athletes may not use IHSA or member-school names, logos, mascots, trademarks or facilities, may not engage in NIL during school hours, travel to/from IHSA events, or during IHSA events, and IHSA recommends athletes work with their principal/official representative on opportunities. Banned industry categories include gambling, alcohol, tobacco, cannabis, banned/illegal substances, adult entertainment, and weapons.",
    sourceLabel: "IHSA By-law 3.084 (NIL)",
    sourceUrl: "https://www.ihsa.org/documents/forms/2025-26/25-26%20School%20Term%201%20Column.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  IN: {
    code: "IN",
    name: "Indiana",
    hsNilAllowed: "off",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "Indiana (IHSAA) does not currently permit NIL for high school athletes under existing amateurism rules. The IHSAA Board of Directors is scheduled to vote on May 4, 2026 on a 'Personal Branding Activity' (PBA) proposal that would allow limited NIL with a 48-hour disclosure rule. Until that vote passes, NIL is prohibited.",
    sourceLabel: "IHSAA Personal Branding Activity proposal coverage (pending May 4, 2026 vote)",
    sourceUrl: "https://www.inkfreenews.com/2026/04/27/is-nil-coming-to-indiana-high-school-sports-ihsaa-will-consider-proposal/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  KS: {
    code: "KS",
    name: "Kansas",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "gambling", "controlled substances", "performance-enhancing supplements"],
    notes: "Kansas (KSHSAA) permits NIL under Rule 21 but the athlete cannot affiliate themselves with their school, team, the KSHSAA, or with school awards in commercial activity. NIL is barred during school hours, school marks/logos cannot be used, and athletes cannot endorse tobacco, alcohol, gambling, banned athletic substances, or illegal substances/activities.",
    sourceLabel: "KSHSAA Rule 21 (Amateur Status and NIL)",
    sourceUrl: "https://www.kshsaa.org/Public/PDF/AmateurStatusNov2021.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  KY: {
    code: "KY",
    name: "Kentucky",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "gambling", "controlled substances", "performance-enhancing supplements"],
    notes: "Kentucky (KHSAA) permits NIL under Bylaw 10 so long as the athlete does not use school name, logos, apparel, or uniforms, and compensation is not tied to athletic performance or promised as an inducement. Endorsements paid at prevailing market rates (and camp/clinic/instruction work) are allowed. The KHSAA Board has directed staff to develop a notification mechanism so athletes report agreements to the school's designated representative.",
    sourceLabel: "KHSAA Bylaw 10 (Amateur Status / NIL)",
    sourceUrl: "https://khsaa.org/common_documents/handbook/2024-2025/2024-25%20Handbook-02-Bylaws.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  LA: {
    code: "LA",
    name: "Louisiana",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "Louisiana (LHSAA) permits NIL under Bylaw 1.25 (Maintaining Amateur Status). The LHSAA takes an 'education, not regulation' approach: deals must not be pay-for-play or recruitment inducements and must not use school marks. The LHSAA partners with Eccker Sports / NIL Club for compliance education.",
    sourceLabel: "LHSAA Bylaw 1.25 / NIL Club press release",
    sourceUrl: "https://www.lhsaa.org/siteuploads/lhsaa/22065_pdf_lhsaa-_-nil-club-press-release-final.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  MA: {
    code: "MA",
    name: "Massachusetts",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "weapons", "controlled substances"],
    notes: "MIAA Rule 47 allows HS NIL but bans use of school name, logo, uniforms, or MIAA marks, and prohibits endorsements during team or tournament activities. Athletes must disclose all endorsement, employment, and representation agreements to their school.",
    sourceLabel: "MIAA Handbook (Rule 47)",
    sourceUrl: "https://www.miaa.net/sites/default/files/2024-04/miaa-handbook-23-25.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  MD: {
    code: "MD",
    name: "Maryland",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "MPSSAA permits HS NIL but bans collectives outright and prohibits any reference to a member school or use of school logos, jerseys, or marks. Video-game endorsements are also prohibited.",
    sourceLabel: "MPSSAA NIL Guidance",
    sourceUrl: "https://www.mpssaa.org/assets/1/6/NIL_Guidance.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  ME: {
    code: "ME",
    name: "Maine",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances", "weapons"],
    notes: "Maine (MPA) permits NIL under Appendix DD of the MPA Handbook (in effect since July 2022). Athletes cannot reference the school or MPA, cannot wear partner apparel or display logos during team activities, and no school employees (coaches, teachers, administrators) may be involved with the athlete's NIL. Banned categories include adult entertainment, alcohol, tobacco, cannabis, controlled substances, prescription pharmaceuticals, casinos/gambling/sports betting, and weapons/firearms/ammunition.",
    sourceLabel: "Maine Principals' Association Handbook, Appendix DD (NIL Policy)",
    sourceUrl: "https://mpaprof.org/wp-content/uploads/2025/07/MPA-Handbook.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  MI: {
    code: "MI",
    name: "Michigan",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements", "weapons", "controlled substances"],
    notes: "MHSAA expanded its Personal Branding Activity (PBA) policy in January 2026 to broadly permit HS NIL, but bans use of school marks, uniforms, and athletic-performance tie-ins. Every PBA agreement must be disclosed to the school and MHSAA within seven days.",
    sourceLabel: "MHSAA Personal Branding Activity Policy",
    sourceUrl: "https://www.mhsaa.com/students/name-image-likeness",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  MN: {
    code: "MN",
    name: "Minnesota",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "weapons", "controlled substances"],
    notes: "MSHSL permits HS NIL provided compensation is at market value, not contingent on athletic performance, and not provided by the school or its agents (boosters, foundations). School and MSHSL marks/logos cannot be used and athletes cannot reference their HS team in promotions.",
    sourceLabel: "MSHSL NIL Policy",
    sourceUrl: "https://www.mshsl.org/sites/default/files/2022-06/9.D_NIL%20Statement%20Draft.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  MO: {
    code: "MO",
    name: "Missouri",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: true,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Under MSHSAA By-Law 3.6 (Amateurism), HS athletes may earn NIL only after signing a National Letter of Intent (or equivalent) with a Missouri postsecondary institution. School marks, colors, mascots, and uniforms can only appear in NIL with advance administrator approval; HS-affiliated NIL collectives are prohibited.",
    sourceLabel: "MSHSAA Official Handbook (By-Law 3.6)",
    sourceUrl: "https://www.mshsaa.org/resources/pdf/Official%20Handbook.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  MS: {
    code: "MS",
    name: "Mississippi",
    hsNilAllowed: "off",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "MHSAA bylaws prohibit HS student-athletes from monetizing NIL; engaging in NIL deals jeopardizes amateur eligibility. A 2026 legislative effort (HB 1400) to authorize HS NIL died in committee, leaving the prohibition in place.",
    sourceLabel: "Athletic Business / MHSAA bylaws",
    sourceUrl: "https://www.athleticbusiness.com/operations/governing-bodies/article/15817027/bill-that-would-allow-nil-opportunities-for-mississippi-high-school-studentathletes-dies-in-committee",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  MT: {
    code: "MT",
    name: "Montana",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "controlled substances", "performance-enhancing supplements"],
    notes: "MHSA adopted an NIL policy under Section 16 (Amateur Rule) in 2025 allowing HS NIL, but with strict separation: no school venues, branded apparel, game film, or in-school promotion, and no school/booster/collective payments. Bans alcohol, tobacco, nicotine/vaping, controlled substances, drug paraphernalia, and gambling.",
    sourceLabel: "Montana High School Association",
    sourceUrl: "https://www.mhsa.org/handbook/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  NC: {
    code: "NC",
    name: "North Carolina",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "NCHSAA NIL became effective after a 2024 court order; minors must have a parent or legal guardian as a party to the agreement, and the student plus parent and key staff must complete the NFHS NIL course annually before the first contest. A copy of every NIL agreement must be provided to the head coach, athletic director, principal, local superintendent, and chair of the local board of education.",
    sourceLabel: "NCHSAA Name, Image and Likeness Resource Page",
    sourceUrl: "https://www.nchsaa.org/name-image-and-likeness/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  ND: {
    code: "ND",
    name: "North Dakota",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "NDHSAA approved NIL in June 2022 via amendment to Section II, Article VIII. Athletes may not use school uniforms, school or league logos, may not be paid for athletic performance, and booster clubs may not facilitate deals. Vice categories (alcohol, tobacco, cannabis, gambling, weapons) are prohibited.",
    sourceLabel: "NDHSAA Constitution and By-Laws",
    sourceUrl: "https://ndhsaa.com/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  NE: {
    code: "NE",
    name: "Nebraska",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "NSAA Bylaw 3.7.1 permits HS NIL on an individual basis, but deals cannot suggest endorsement by an NSAA member school and cannot use the student in school uniform or with school logos. Violations may result in loss of eligibility.",
    sourceLabel: "NSAA Name, Image, Likeness Policy",
    sourceUrl: "https://nsaa-static.s3.amazonaws.com/textfile/yb/NIL.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  NH: {
    code: "NH",
    name: "New Hampshire",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "NHIAA amended its amateur rules in late 2022 to allow HS NIL through commercial endorsements with no school/team/NHIAA affiliation; athletes cannot appear in school uniform or use school or NHIAA marks. Athletes may also accept up to $1,000 in prize money without losing amateur status.",
    sourceLabel: "NHIAA Handbook",
    sourceUrl: "https://www.nhiaa.org/about-nhiaa/handbook",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  NJ: {
    code: "NJ",
    name: "New Jersey",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "NJSIAA permits NIL since January 2022; deals must not reference school name, mascot, logo or use the school uniform, and no school employee may facilitate deals. Endorsements involving alcohol, tobacco, cannabis, gambling, weapons, adult content and controlled substances are prohibited.",
    sourceLabel: "NJSIAA Name, Image and Likeness FAQs (Updated May 2025)",
    sourceUrl: "https://www.njsiaa.org/sites/default/files/documents/2022-01/njsiaa-nil-faqs-final.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  NM: {
    code: "NM",
    name: "New Mexico",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "NMAA Bylaw 6.18.3 (adopted June 2023) permits commercial endorsements provided there is no school, school team, or NMAA affiliation; uniforms, marks and logos may not be used. Specific banned-category list is not published in the bylaw, so the standard high-school vice-category restrictions are used here as a safe default.",
    sourceLabel: "NMAA Bylaws Section VI (6.18.3) - New Mexico Activities Association",
    sourceUrl: "https://www.nmact.org/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  NV: {
    code: "NV",
    name: "Nevada",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "weapons", "controlled substances"],
    notes: "NIAA approved HS NIL in April 2023 but only for sports the NIAA does not sanction; athletes in NIAA-sponsored sports (football, basketball, baseball, etc.) face significant NIL restrictions. Bans adult entertainment, tobacco, cannabis, controlled substances, weapons, and gambling.",
    sourceLabel: "Eccker Sports / NIAA",
    sourceUrl: "https://ecckersports.com/industry-insights/nevada-is-now-the-28th-state-to-allow-for-name-image-and-likeness-as-the-high-school-level/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  NY: {
    code: "NY",
    name: "New York",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "minor-only",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "NYSPHSAA revised its amateur rule in October 2021 to allow NIL; deals may not reference the school, Section, or NYSPHSAA, and may not use uniforms, logos or facilities. Because contracts with minor performers in New York may require court approval under N.Y. Arts & Cultural Affairs Law Article 35, families should treat parent cosignature plus notarization as a baseline for any longer-term endorsement deal.",
    sourceLabel: "NYSPHSAA Handbook (Aug 2025) and NYSPHSAA Eligibility Rules",
    sourceUrl: "https://nysphsaa.org/documents/2023/8/21/NYSPHSAA_Handbook_Aug_2025.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  OH: {
    code: "OH",
    name: "Ohio",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "required",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "OHSAA member schools approved Bylaw 4-11 (Name, Image & Likeness/Personal Branding Rights) by referendum on November 24, 2025, making Ohio the 45th state to permit HS NIL. Both the student and a parent must sign a notarized Affirmation, and each agreement must be reported to OHSAA within 14 days via the Personal Branding Rights Parent Portal; failure to disclose can result in up to a 20% season suspension. Pay-for-play, recruiting inducements, school marks, and vice categories (gambling, adult content, alcohol, tobacco, controlled substances, etc.) are banned.",
    sourceLabel: "OHSAA NIL Resource Center - Bylaw 4, Section 11",
    sourceUrl: "https://www.ohsaa.org/Eligibility/NIL-Resource-Center",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  OK: {
    code: "OK",
    name: "Oklahoma",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "OSSAA NIL guidelines (effective 2022) permit NIL provided compensation is not contingent on athletic performance, is not used as an enrollment inducement, and is not provided by the school or its agents. School marks, logos, mascots, uniforms and facilities may not be used, and any activity violating local district policy (e.g., tobacco or alcohol) is prohibited.",
    sourceLabel: "OSSAA Guidelines Regarding Name, Image and Likeness",
    sourceUrl: "http://www.ossaa.net/docs/2022-23/MiscForms/MF_2022-23_NILGuidelines.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  OR: {
    code: "OR",
    name: "Oregon",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "OSAA Rule 8.4 (Awards/NIL), approved October 2022, permits NIL provided compensation is not performance-contingent and is not an enrollment inducement. Athletes must disclose agreements to their member school; OSAA or member-school marks, logos, uniforms, facilities and game film may not be used, and athletes may not promote products during team activities. Vice categories (alcohol, tobacco, cannabis, vaping, gambling, adult entertainment) are banned.",
    sourceLabel: "OSAA Handbook - Rule 8.4 (Name, Image, Likeness)",
    sourceUrl: "https://www.osaa.org/docs/handbooks/osaahandbook.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  PA: {
    code: "PA",
    name: "Pennsylvania",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "PIAA approved NIL on December 7, 2022; athletes must disclose any NIL agreement to their principal or athletic director within 72 hours of signing. Banned endorsement categories include adult entertainment, alcohol, casinos and gambling (including sports betting and lottery), tobacco and electronic smoking products, opioids and prescription pharmaceuticals, controlled dangerous substances, and weapons/firearms/ammunition. Repeated violations follow a three-strikes rule up to permanent loss of eligibility.",
    sourceLabel: "PIAA Handbook - NIL Policy",
    sourceUrl: "https://www.piaa.org/resources/handbook/default.aspx",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  RI: {
    code: "RI",
    name: "Rhode Island",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances"],
    notes: "RIIL became the 21st state to permit HS NIL in November 2022; athletes may monetize NIL only if there is no connection with the team, school, or RIIL (no uniforms, marks, logos, or facilities). RIIL has not published a detailed banned-category list separate from amateur-status rules, so standard vice-category restrictions are applied here as a safe default; athletes should confirm specifics with their school.",
    sourceLabel: "Rhode Island Interscholastic League - Rules & Regulations",
    sourceUrl: "https://www.riil.org/index.php/resources/rules-and-regulations",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  SC: {
    code: "SC",
    name: "South Carolina",
    hsNilAllowed: "off",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "South Carolina prohibits high school NIL. SCHSL amended its bylaws in June 2025 to explicitly bar student-athletes from earning compensation, after a state budget clause required public school districts to affiliate only with associations that prohibit NIL. Violations risk warnings and one-year suspensions.",
    sourceLabel: "SCHSL NIL Update / Athletic Business",
    sourceUrl: "https://www.athleticbusiness.com/operations/governing-bodies/article/15749065/south-carolina-moves-to-ban-nil-deals-for-high-school-athletes",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  SD: {
    code: "SD",
    name: "South Dakota",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "controlled substances", "performance-enhancing supplements"],
    notes: "SDHSAA approved a constitutional amendment permitting NIL effective July 1, 2024, with 11 guiding principles. No pay-for-play, no school/booster involvement, no school marks/logos/uniforms, and no endorsements of alcohol, tobacco, vaping, controlled substances, gambling, or banned athletic substances.",
    sourceLabel: "SDHSAA NIL Policy",
    sourceUrl: "https://www.dakotanewsnow.com/2024/06/12/sdhsaa-approves-new-nil-guidelines-high-school-athletes/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  TN: {
    code: "TN",
    name: "Tennessee",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "TSSAA has allowed HS NIL since December 2022. Athletes may not appear in school uniforms or reference TSSAA accolades. Coaches, schools, and booster clubs cannot facilitate, coordinate, or fund NIL deals. First violation triggers a warning; repeat violations risk 12-month sport-specific ineligibility.",
    sourceLabel: "TSSAA NIL & Amateur Rule",
    sourceUrl: "https://tssaa.org/name-image-likeness",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  TX: {
    code: "TX",
    name: "Texas",
    hsNilAllowed: "partial",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Texas UIL allows HS NIL only in a limited form: prospective student-athletes age 17+ may sign NIL agreements, but only with colleges/universities, and payment cannot begin until they enroll in college and exhaust UIL eligibility. NIL deals with all other entities (brands, collectives, individuals) remain prohibited during HS eligibility.",
    sourceLabel: "UIL NIL Information (2024-25)",
    sourceUrl: "https://www.uiltexas.org/policy/2024-25-policy-info/nil-information",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  UT: {
    code: "UT",
    name: "Utah",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "UHSAA has permitted HS NIL since January 2022. Athletes may not wear school uniforms or insignia in any advertisement, promotion, or endorsement, and may not lend their name with team affiliation for commercial endorsement. Pay-for-play and school/booster-driven deals are prohibited.",
    sourceLabel: "UHSAA Handbook 2025-26",
    sourceUrl: "https://uhsaa.org/Publications/Handbook/Handbook.pdf",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  VA: {
    code: "VA",
    name: "Virginia",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: true,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "VHSL adopted an NIL policy effective July 1, 2023. Athletes must notify their principal or athletic director in writing within 72 hours of signing any NIL contract. School IP, uniforms, and recruiting inducements are prohibited; banned categories include adult entertainment, alcohol, tobacco, prescription pharmaceuticals, gambling/sports betting, and weapons/firearms.",
    sourceLabel: "VHSL NIL Policy / Williams Mullen Summary",
    sourceUrl: "https://www.williamsmullen.com/insights/news/legal-news/virginia-high-school-league-adopts-name-image-and-likeness-guidelines",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  VT: {
    code: "VT",
    name: "Vermont",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Vermont Principals' Association (VPA) bylaws permit HS NIL. Athletes cannot reference the VPA or member school, wear school jerseys/logos, or endorse during school team activities. Banned categories include adult entertainment, alcohol, tobacco/nicotine/vape, cannabis, prescription pharmaceuticals, gambling, and firearms.",
    sourceLabel: "Vermont Principals' Association NIL Policy",
    sourceUrl: "https://ecckersports.com/vermont/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  WA: {
    code: "WA",
    name: "Washington",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Washington WIAA permits HS NIL under handbook section 18.24.0. Commercial endorsements are allowed provided there is no affiliation with the school team, school, WIAA District, or WIAA — meaning no school name, logo, or uniform may be used. Athletes have begun signing local endorsement deals.",
    sourceLabel: "WIAA Handbook (Washington)",
    sourceUrl: "https://www.union-bulletin.com/sports/college_sports/university_of_washington/nil-officially-reaches-high-schools-in-wa-two-tacoma-football-stars-ink-deals/article_1a591678-f17b-573c-8a06-3fcd02a9340d.html",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  WI: {
    code: "WI",
    name: "Wisconsin",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Wisconsin WIAA membership approved HS NIL on April 25, 2025 (293-108 vote), effective late May 2025. No school/conference/WIAA mentions, uniforms, or logos in deals. Athletes cannot use agents or professional representation, and no school-affiliated person (coach, parent of teammate, booster) can fund or facilitate deals. Banned: alcohol, tobacco, gambling, firearms, adult entertainment, and age-inappropriate products.",
    sourceLabel: "WIAA NIL Rule (Boardman Clark summary)",
    sourceUrl: "https://www.boardmanclark.com/publications/school-law-fyi/wiaa-approves-nil-rule",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  WV: {
    code: "WV",
    name: "West Virginia",
    hsNilAllowed: "on",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "controlled substances", "performance-enhancing supplements"],
    notes: "WVSSAC approved an NIL policy effective August 8, 2025, covering both high school and middle school athletes. Athletes cannot reference the school or wear school logos, school employees and coaches cannot be involved, and NIL cannot be promoted during team activities. Banned categories include alcohol, tobacco, cannabis, controlled substances, adult entertainment, gambling, and weapons.",
    sourceLabel: "WVSSAC NIL Policy",
    sourceUrl: "https://www.wtrf.com/west-virginia/west-virginia-approves-policy-for-high-school-middle-school-athletes-to-make-money/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
  WY: {
    code: "WY",
    name: "Wyoming",
    hsNilAllowed: "off",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: ["alcohol", "tobacco", "cannabis", "gambling", "firearms", "adult content", "performance-enhancing supplements"],
    notes: "Wyoming prohibits HS NIL. The WHSAA's 2025 proposal to allow NIL was defeated, and in March 2026 Governor Mark Gordon signed Senate File 53 (\"Keeping Amateurism in High School Athletics\") into law, codifying the amateurism requirement for any student in WHSAA-sanctioned sports. Receiving money or gifts of monetary value for athletic fame forfeits eligibility.",
    sourceLabel: "Cowboy State Daily — Gordon Signs HS NIL Ban",
    sourceUrl: "https://cowboystatedaily.com/2026/03/03/gordon-signs-bill-to-keep-nil-money-out-of-wyoming-high-school-sports/",
    lastUpdated: "2026-04-29",
    documented: true,
  },
};

const STATE_NAMES_FULL: Record<string, string> = {
  AL: "Alabama", AK: "Alaska", AZ: "Arizona", AR: "Arkansas", CA: "California",
  CO: "Colorado", CT: "Connecticut", DE: "Delaware", DC: "District of Columbia",
  FL: "Florida", GA: "Georgia", HI: "Hawaii", ID: "Idaho", IL: "Illinois",
  IN: "Indiana", IA: "Iowa", KS: "Kansas", KY: "Kentucky", LA: "Louisiana",
  ME: "Maine", MD: "Maryland", MA: "Massachusetts", MI: "Michigan", MN: "Minnesota",
  MS: "Mississippi", MO: "Missouri", MT: "Montana", NE: "Nebraska", NV: "Nevada",
  NH: "New Hampshire", NJ: "New Jersey", NM: "New Mexico", NY: "New York",
  NC: "North Carolina", ND: "North Dakota", OH: "Ohio", OK: "Oklahoma",
  OR: "Oregon", PA: "Pennsylvania", RI: "Rhode Island", SC: "South Carolina",
  SD: "South Dakota", TN: "Tennessee", TX: "Texas", UT: "Utah", VT: "Vermont",
  VA: "Virginia", WA: "Washington", WV: "West Virginia", WI: "Wisconsin",
  WY: "Wyoming",
};

function stubFor(code: string): StateRules {
  return {
    code,
    name: STATE_NAMES_FULL[code] ?? code,
    hsNilAllowed: HS_NIL_STATUS[code] ?? "off",
    parentalConsentRequired: true,
    parentalCosignOnDeals: true,
    notarization: "none",
    schoolApprovalRequired: false,
    schoolDisclosureRequired: false,
    bannedCategories: STANDARD_BANNED,
    notes:
      "Documentation in progress. Detailed rules for this state have not yet been verified. Treat parental co-signature as required and consult your school's athletic director before signing any deal.",
    lastUpdated: "2026-04-27",
    documented: false,
  };
}

export const STATE_RULES: Record<string, StateRules> = (() => {
  const all: Record<string, StateRules> = { ...SEEDED };
  for (const code of Object.keys(STATE_NAMES_FULL)) {
    if (!all[code]) all[code] = stubFor(code);
  }
  return all;
})();

export function rulesFor(code: string | null | undefined): StateRules | null {
  if (!code) return null;
  return STATE_RULES[code.toUpperCase()] ?? null;
}

export function allStateRules(): StateRules[] {
  return Object.values(STATE_RULES).sort((a, b) => a.name.localeCompare(b.name));
}
